name: 'Build LaTex Document'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: wtfjoke/setup-tectonic@v3
      - name: Run Tectonic
        run: tectonic sample-sigconf.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: sample-sigconf.pdf